
# Определение локаций игры.



image adm = "images/lok/adminictraciya.jpg"
image bibliotk_vnt = "images/lok/biblioteca_vntr.jpg"
image bibliotk_vnt_2 = "images/lok/biblioteka_vnt_2.jpg"
image bibl = "images/lok/biblioteka.jpg"
image bufet = "images/lok/bufet.jpg"
image cokol_kor = "images/lok/cokol_kor.jpg"
image cokol_ping = "images/lok/cokol_ping.jpg"
image docka_pochet = "images/lok/docka_pochet.jpg"
image garderob = "images/lok/garderob.jpg"
image holl_2 = "images/lok/holl_2.jpg"
image holl = "images/lok/holl.jpg"
image hot_dog = "images/lok/hot_dog.jpg"
image kab_107_vnt = "images/lok/kab_107_vnt.jpg"
image kab_107 = "images/lok/kab_107.jpg"
image kaf_fin_ych = "images/lok/kaf_fin_ych.jpg"
image kol_kor_per = "images/lok/kol_kor_per.jpg"
image kol_kor_vt = "images/lok/kol_kor_vt.jpg"
image kol_lec = "images/lok/kol_lec.jpg"
image kor_tret = "images/lok/kor_tret.jpg"
image kor_vtor_vtor = "images/lok/kor_vtor_vtor.jpg"
image krasn_kor_vtor = "images/lok/krasn_kor_vtor.jpg"
image krasn_kor = "images/lok/krasn_kor.jpg"
image lec_1_1 = "images/lok/lec_1_1.jpg"
image lec_1_2 = "images/lok/lec_1_2.jpg"
image lec_1_3 = "images/lok/lec_1_3.jpg"
image lec_2_2 = "images/lok/lec_2_2.jpg"
image lec_2_3 = "images/lok/lec_2_3.jpg"
image lec_3_3 = "images/lok/lec_3_3.jpg"
image lec_kol_2 = "images/lok/lec_kol_2.jpg"
image naych_obch = "images/lok/naych_obchestvo.jpg"
image priem_kab = "images/lok/priem_kab.jpg"
image pyt_kor_od = "images/lok/pyt_kor_od.jpg"
image pyt_kor_vt = "images/lok/pyt_kor_vt.jpg"
image rabot = "images/lok/rabot.jpg"
image stend_kubki = "images/lok/stend_kubki.jpg"
image stol_stoli = "images/lok/stol_stoli.jpg"
image stud_dver = "images/lok/stud_dver.jpg"
image stud_jizn = "images/lok/stud_jizn.jpg"
image stud_sovet = "images/lok/stud_sovet.jpg"
image tret_dal_kor = "images/lok/tret_dal_kor.jpg"
image vuz_menu = "images/lok/vuz_menu.jpg"
image vuz_nagradi = "images/lok/vuz_nagradi.jpg"
image ved_prepod = "images/lok/ved_prepod.jpg"
image turnik_kol = "images/lok/turnik_kol.jpg"
image kol_itazh = "images/lok/kol_1itazh.jpeg"
image kol_kab = "images/lok/kol_kab.jpg"
image kab_pyt_vn = "images/lok/kab_pyt_vn.jpg"

image kabinet = "images/lok/kabinetik.jpg"
image kabinet_dva = "images/lok/kabinet_dva.jpg"
image kabinet_komp = "images/lok/kabinet_komp.jpg"

image prizivnik = "images/lok/priziv.jpg"
image vipusk = "images/lok/vipesknoy.jpg"

image blek = "images/lok/blak.png"